item {
      id: 1
      name: 'pepper'
}
item {
     id: 2
     name: 'pot'
}
item {
     id: 3
     name: 'stem'
}
item {
     id: 4
     name: 'flower'
}
item {
     id: 5
     name: 'leaf'
}
item {
     id: 6
     name: 'peduncle'
}
